package views;

/**
 * @author Bruno Buiret (bruno.buiret@etu.univ-lyon1.fr)
 * @author Thomas Arnaud (thomas.arnaud@etu.univ-lyon1.fr)
 * @author Alexis Rabilloud (alexis.rabilloud@etu.univ-lyon1.fr)
 */
public class AccountTab extends javax.swing.JPanel
{
    /**
     * Creates new form AccountTab
     */
    public AccountTab()
    {
        this.initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        mailsList = new javax.swing.JList<>();
        mailPane = new javax.swing.JPanel();
        actionsPane = new javax.swing.JPanel();
        answerButton = new javax.swing.JButton();
        answerAllButton = new javax.swing.JButton();
        forwardButton = new javax.swing.JButton();
        senderLabel = new javax.swing.JLabel();
        senderField = new javax.swing.JTextField();
        subjectLabel = new javax.swing.JLabel();
        subjectField = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        mailView = new javax.swing.JTextPane();

        setLayout(new java.awt.GridBagLayout());

        mailsList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(mailsList);

        jSplitPane1.setLeftComponent(jScrollPane1);

        java.awt.GridBagLayout mailPaneLayout = new java.awt.GridBagLayout();
        mailPaneLayout.columnWidths = new int[] {0, 5, 0};
        mailPaneLayout.rowHeights = new int[] {0, 5, 0, 5, 0, 5, 0};
        mailPane.setLayout(mailPaneLayout);

        actionsPane.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        answerButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/mail-reply.png"))); // NOI18N
        answerButton.setText("Répondre");
        actionsPane.add(answerButton);

        answerAllButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/mail-reply-all.png"))); // NOI18N
        answerAllButton.setText("Répondre à tous");
        actionsPane.add(answerAllButton);

        forwardButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/mail-forward.png"))); // NOI18N
        forwardButton.setText("Transférer");
        actionsPane.add(forwardButton);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        mailPane.add(actionsPane, gridBagConstraints);

        senderLabel.setText("Expéditeur");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        mailPane.add(senderLabel, gridBagConstraints);

        senderField.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        mailPane.add(senderField, gridBagConstraints);

        subjectLabel.setText("Sujet");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        mailPane.add(subjectLabel, gridBagConstraints);

        subjectField.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        mailPane.add(subjectField, gridBagConstraints);

        mailView.setEditable(false);
        jScrollPane2.setViewportView(mailView);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 5);
        mailPane.add(jScrollPane2, gridBagConstraints);

        jSplitPane1.setRightComponent(mailPane);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(jSplitPane1, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel actionsPane;
    private javax.swing.JButton answerAllButton;
    private javax.swing.JButton answerButton;
    private javax.swing.JButton forwardButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel mailPane;
    private javax.swing.JTextPane mailView;
    private javax.swing.JList<String> mailsList;
    private javax.swing.JTextField senderField;
    private javax.swing.JLabel senderLabel;
    private javax.swing.JTextField subjectField;
    private javax.swing.JLabel subjectLabel;
    // End of variables declaration//GEN-END:variables
}
